server:
  port: 0
spring:
  boot:
    admin:
      client:
        url:
        - http://localhost:8888
  data:
    mongodb:
      host: localhost
      port: 27017
      database: demo1
  zipkin:
    base-url: http://localhost:9411
  main:
    allow-bean-definition-overriding: true
  
      
  application:
    name: forex-rate-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8889/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
logging:
  file:
    name: forex-rate-service.log 